# Generated by Django 5.1.7 on 2025-03-23 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_alter_snippet_highlighted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='owner',
        ),
    ]
